bon_plan_user:
    resource: "@BonPlanUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /msg

bon_plan_client:
    resource: "@BonPlanClientBundle/Resources/config/routing.yml"
    prefix:   /client

bon_plan_admin:
    resource: "@BonPlanAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

login_check:
    path: /login_check