bon_plan_client_homepage:
    path:     /
    defaults: { _controller: BonPlanClientBundle:Default:index }

bon_plan_resultat:
    path:     /resultat/{type}
    defaults: { _controller: BonPlanClientBundle:Front:resultat }

bon_plan_home:
    path:     /home
    defaults: { _controller: BonPlanClientBundle:Front:index }

bon_plan_inscriEntreprise:
    path:     /inscriEntreprise
    defaults: { _controller: BonPlanClientBundle:Front:inscriEntreprise }

bon_plan_inscriClient:
    path:     /inscriClient
    defaults: { _controller: BonPlanClientBundle:Front:inscriClient }

insert_review:
    path:     /insertReview
    defaults: { _controller: BonPlanClientBundle:Review:new }

affich_review:
    path:     /affichReview
    defaults: { _controller: BonPlanClientBundle:Review:index }

delete_review:
    path:     /deleteReview/{id}/{idcompany}
    defaults: { _controller: BonPlanClientBundle:Review:delete }

edit_review:
    path:     /editReview
    defaults: { _controller: BonPlanClientBundle:Review:edit }

direction_edit_review:
    path:     /dire/{id}/{idcompany}
    defaults: { _controller: BonPlanClientBundle:Review:directionEdit }

page_review:
    path:     /pageReview/{id}
    defaults: { _controller: BonPlanClientBundle:Review:donnerReview }


ajout_company:
    path:     /ajouterCompany
    defaults: { _controller: BonPlanClientBundle:Company:new }

delete_company:
    path:     /deleteCompany/{id}
    defaults: { _controller: BonPlanClientBundle:Company:delete }

company_page:
    path:     /pageCompany/{id}
    defaults: { _controller: BonPlanClientBundle:Company:pageCompany }